[client]
local_addr = "127.0.0.1:8080"
remote_addr = "127.0.0.1:8081"
domain_name = "mydomain.com"
ca_certificate = "./tls_config/rootCA.crt"

[server]
local_addr = "127.0.0.1:8081"
remote_addr = "127.0.0.1:8082"
server_cert = "./tls_config/mydomain.com.crt"
server_key = "./tls_config/mydomain.com.key"
